### ISSUE TITLE
Slice bounds out of range in decodeLineOfMediaPlaylist.

### ISSUE THREAD

**Issue by koltiradw** [khenarghot/m3u8#1]
Hi! I found slice bounds out of range ( occurs at reader.go:840) during testing with go-fuzz.

- Crash artifacts - [crash.zip](https://github.com/khenarghot/m3u8/files/8850364/crash.zip)

- Harness - [fuzz.zip](https://github.com/khenarghot/m3u8/files/8850369/fuzz.zip)

 ## P. S:
Perhaps I described an incorrect wrapper and therefore am open to criticism.

**Comment by khenarghot** [comment]
Fixed
