### ISSUE TITLE
Invalid memory address or nil pointer dereference.

### ISSUE THREAD

**Issue by koltiradw** [khenarghot/m3u8#2]
Hi! I found runtime error  ( occurs at reader.go:571) during testing with go-fuzz.

- Crash artifacts - [crash.zip](https://github.com/khenarghot/m3u8/files/8850385/crash.zip)

- Harness - [fuzz.zip](https://github.com/khenarghot/m3u8/files/8850386/fuzz.zip)

 ## P. S:
Perhaps I described an incorrect wrapper and therefore am open to criticism.

**Comment by khenarghot** [comment]
Currently not reproduced!
