### ISSUE TITLE
Slice bounds out of range in decodeLineOfMediaPlaylist #2.

### ISSUE THREAD

**Issue by koltiradw** [khenarghot/m3u8#3]
Hi! I found slice bounds out of range ( occurs at reader.go:796 ) during testing with go-fuzz.

- Crash artifacts - [crash.zip](https://github.com/khenarghot/m3u8/files/8850400/crash.zip)

- Harness -  [fuzz.zip](https://github.com/khenarghot/m3u8/files/8850401/fuzz.zip)

 ## P. S:
Perhaps I described an incorrect wrapper and therefore am open to criticism.

**Comment by khenarghot** [comment]
Fix it
