### ISSUE TITLE
Mismatch bug

### ISSUE THREAD

**Issue by koltiradw** [khenarghot/m3u8#4]
Hi I found this bug during testing with go-fuzz. 

I proceeded from the fact that the buffer after decoding and encoding should be the same as the original one.

- Crash artifacts - [crash.zip](https://github.com/khenarghot/m3u8/files/8850418/crash.zip)

- Harness - [fuzz.zip](https://github.com/khenarghot/m3u8/files/8850417/fuzz.zip)

 ## P. S:
Perhaps I described an incorrect wrapper and therefore am open to criticism.

**Comment by khenarghot** [comment]
Such playlist should cause error in strict decode mode. This has been fixed.

But this check is incorrect. Encoded playlist may be differ from original one. Tags can be reordered and some custom tags may be lost.
